### PR TITLE
Make csprojs consistent

### PR DESCRIPTION
**Pull request by Morilli**
- use the same icon for every nuget package
- fixate `LangVersion` to 11 for all projects
- summary of the rest of the changes is left as an exercise to the reader

### CODE REVIEW

**Comment by Rerago** [comment]
What would speak against `<LangVersion>latest</LangVersion>`? That would be `11` in our case and it would not need to be touched again later.

We could also use `Directory.Build.Targets` and `Directory.Build.Props`. Then we would not have to set many of the properties in each project and we would only have to maintain one location.

**Comment by Crauzer** [comment]
The issue with the msbuild config bs is the documentation, I've spent hours trying to understand how it works by reading the docs but I still have no idea.

#230

**Review by Crauzer — APPROVED** [review]
optional: use latest lang version

**Review by Crauzer — APPROVED** [review]
@Morilli Thanks for doing the props thing, I'm a total noob with these configs.

**Pull request merged**
